version: '3.6'
services:
  mongodb:
    image: mongo
    container_name: webscraping_mongo
    ports:
        - '27017:27017'
    user: '0' #root user
    volumes:
          - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
          - ./webshops_backup:/data/db
          - ./webshops_restore:/data_restore/db
    restart: always
    environment:
          - MONGO_INITDB_DATABASE=db_name
          - MONGO_INITDB_ROOT_USERNAME=username
          - MONGO_INITDB_ROOT_PASSWORD=password
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
        - '3000:3000'
    user: '0' #root user
    volumes:
          - ./grafana_lib:/var/lib/grafana
    restart: always
    environment:
          - GF_INSTALL_PLUGINS=marcusolsson-json-datasource,simpod-json-datasource,yesoreyeram-infinity-datasource,grafana-piechart-panel, magnesium-wordcloud-panel, marcusolsson-hexmap-panel, digrich-bubblechart-panel, grafana-clock-panel, grafana-worldmap-panel
  flask:
    build: ./flask
    container_name: flask
    ports:
        - '5000:5000'
    user: '0' #root user
    restart: always
